### PR TITLE
Support for the use of different registries

### PR DESCRIPTION
**Pull request by RainerHausdorf**
Until now it is not possible with graphene_django_plus to use more than one ModelType for a django model, because internally the global registry is always used. This pull request adds support for a registry parameter analogous to the registry parameter in DjangoObjectType for mutations.

### CODE REVIEW

**Comment by bellini666** [comment]
Hey @RainerHausdorf ,

Thanks for the contribution! The change LGTM, you just need to adjust the linting to make it pass (tip: use `pre-commit` that will automatically fix the issue for you)

**Comment by RainerHausdorf** [comment]
@bellini666 Thanks for the quick reply. I have corrected it with `pre-commit`.

**Comment by bellini666** [comment]
Thanks! Going to make a new release with it :)

**Comment by RainerHausdorf** [comment]
@bellini666 Perfect. Thank you very much!

**Pull request merged**
